application: StartupPitchPerfect
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /js
  static_dir: js

- url: /test
  static_dir: test

- url: /plugin
  static_dir: plugin

- url: /.*
  script: main.application

libraries:
- name: jinja2
  version: latest
